apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_TTL_MINUTES
              value: "60"
            - name: DB_DSN
              value: postgres://postgres:postgres@auth-db:5432/auth?sslmode=disable
            - name: HTTP_PORT
              value: "50052"
            - name: JWT_SECRET
              value: secret
            - name: REFRESH_TOKEN_TTL_DAYS
              value: "30"
          image: local-env-auth:latest
          imagePullPolicy: IfNotPresent
          name: auth
          ports:
            - containerPort: 50052
              protocol: TCP
      restartPolicy: Always
