apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: transaction
  name: transaction
spec:
  ports:
    - name: "50054"
      port: 50054
      targetPort: 50054
  selector:
    io.kompose.service: transaction
