// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

package mocks

import (
	context "context"
	reflect "reflect"

	model "transaction/internal/model"

	gomock "go.uber.org/mock/gomock"
)

type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

func (m *MockRepository) GetTransactions(ctx context.Context, params model.GetTransactionsParams) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, params)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) GetTransactions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockRepository)(nil).GetTransactions), ctx, params)
}

func (m *MockRepository) GetTransactionDetails(ctx context.Context, transactionID uint64) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionDetails", ctx, transactionID)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) GetTransactionDetails(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionDetails", reflect.TypeOf((*MockRepository)(nil).GetTransactionDetails), ctx, transactionID)
}

func (m *MockRepository) Deposit(ctx context.Context, params model.DepositParams) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", ctx, params)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) Deposit(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockRepository)(nil).Deposit), ctx, params)
}

func (m *MockRepository) Withdraw(ctx context.Context, params model.WithdrawParams) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, params)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) Withdraw(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockRepository)(nil).Withdraw), ctx, params)
}

func (m *MockRepository) Transfer(ctx context.Context, params model.TransferParams) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, params)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) Transfer(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockRepository)(nil).Transfer), ctx, params)
}

func (m *MockRepository) UpdateTransactionStatus(ctx context.Context, transactionID uint64, status model.TransactionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, transactionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) UpdateTransactionStatus(ctx, transactionID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionStatus), ctx, transactionID, status)
}

type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
}

type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

func (m *MockAccountService) GetBalance(ctx context.Context, userID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockAccountService)(nil).GetBalance), ctx, userID)
}

func (m *MockAccountService) Deposit(ctx context.Context, userID uint64, amount int64, operationID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", ctx, userID, amount, operationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountServiceMockRecorder) Deposit(ctx, userID, amount, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockAccountService)(nil).Deposit), ctx, userID, amount, operationID)
}

func (m *MockAccountService) Withdraw(ctx context.Context, userID uint64, amount int64, operationID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, amount, operationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountServiceMockRecorder) Withdraw(ctx, userID, amount, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockAccountService)(nil).Withdraw), ctx, userID, amount, operationID)
}

func (m *MockAccountService) Transfer(ctx context.Context, fromAccountID, toAccountID uint64, amount int64, operationID uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromAccountID, toAccountID, amount, operationID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountServiceMockRecorder) Transfer(ctx, fromAccountID, toAccountID, amount, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockAccountService)(nil).Transfer), ctx, fromAccountID, toAccountID, amount, operationID)
}

type MockKafkaPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaPublisherMockRecorder
}

type MockKafkaPublisherMockRecorder struct {
	mock *MockKafkaPublisher
}

func NewMockKafkaPublisher(ctrl *gomock.Controller) *MockKafkaPublisher {
	mock := &MockKafkaPublisher{ctrl: ctrl}
	mock.recorder = &MockKafkaPublisherMockRecorder{mock}
	return mock
}

func (m *MockKafkaPublisher) EXPECT() *MockKafkaPublisherMockRecorder {
	return m.recorder
}

func (m *MockKafkaPublisher) Publish(ctx context.Context, topic string, key string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockKafkaPublisherMockRecorder) Publish(ctx, topic, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockKafkaPublisher)(nil).Publish), ctx, topic, key, data)
}
